version: '3.8'

name: 'start-kehet-com'

services:

  nginx:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - NGINX_HOST=start.kehet.com

networks:
  default:
    external: true
    name: scoobydoo
